function p = linearAnAParams()
    home = '/home/josh/data/ruleRiesenhuber2013/';
    imgDir = [home 'imageSets/animalNoAnimal/'];
    patchDir = [home 'patchSets/'];
    patchSets = {'kmeans','twoOhOhSeven','random','randomTwoThirds'};

    p = struct( ...
        'home', home, ...
        'srcPath', [home 'src/'], ...
        'imgHome', '/home/josh/maxlab/image-sets/image-net/images/', ...
        'imgDir', imgDir, ...
        'outDir', ensureDir([home 'evaluation/AnASmall/']), ...
        'patchDir', ensureDir(patchDir), ...
        'organicC3Dir', ensureDir([patchDir 'kmeans-organicC3vLinear/']), ...
        'inorganicC3Dir', ensureDir([patchDir 'kmeans-inorganicC3vLinear/']), ...
        'nCategories', 1, ...
        'seed', 0, ...
        'nTrainingExamples', [2 4 8], ...
        'nTestingFeats', [1 2 4 8 16 32 48 64 96 128 192 256 384 512 768 1024 2000 2056], ...
        'nTestingCategories', 2, ...
        'nTestingThreshes', [0.3:.05:.9], ...
        'nVisualThreshes', [0.9:.005:0.995], ...
        'nRuns', 40, ...
        'method', 'svm', ...
        'options', '-s 0 -t 0 -b 1 -q -c 0.1', ...
        'c2PatchSets', {patchSets}, ...
        'c3PatchSets', {'kmeans'}, ...
        'caching', struct( ...
            'cacheDir', ensureDir([imgDir 'c2Cache/']), ...
            'maxSize', 256, ...
            'patchDir', [home 'patchSets/'], ...
            'hmaxHome', [home 'src/hmax-ocv/'], ...
            'nImgs', 600));
end

function success = ensureDir(dirName)
% Author: Santosh Divvala
% Revised: saurabh.me@gmail.com (Saurabh Singh).
% Revised: rsj28@georgetown.edu (Josh Rule).
%
% Conditionally create a directory and return its path
%
% dirName: string, the absolute path of the directory
%
% success: string, the absolute path of the directory, empty on failure
    if exist(dirName, 'dir') || mkdir(dirName)
        success = dirName;
    else
        success = '';
    end
end
