function [home,p] = Linear5050Params()
    home = '/home/josh/data/ruleRiesenhuber2013';
    suffix = 'Linear';
    imgDir = [home 'imageSets/imageNet/'];
    patchSet = 'kmeans';

    p = struct( ...
        'home', home, ...
        'suffix', suffix, ...
        'imgHome', '/home/josh/maxlab/image-sets/image-net/', ...
        'imgDir', imgDir, ...
        'outDir', ensureDir([home 'evaluation/5050v' suffix '/']), ...
        'organicCatFile', [imgDir 'organicCategories.mat'], ...
        'inorganicCatFile', [imgDir 'inorganicCategories.mat'], ...
        'organicImgDir', [imgDir 'organicC2Cache/'], ...
        'inorganicImgDir', [imgDir 'inorganicC2Cache/'], ...
        'organicC3Dir', [home 'patchSets/organicC3v' suffix '/'], ...
        'inorganicC3Dir', [home 'patchSets/inorganicC3v' suffix '/'], ...
        'seed', 0, ...
        'nTrainingExamples', [16 32 64 128 256], ...
        'nRuns', 20, ...
        'method', 'svm', ...
        'options', '-s 0 -t 0 -b 1 -q -c 0.1', ...
        'patchSet', patchSet, ...
        'caching', struct( ...
            'maxSize', 240, ...
            'patchFile', [home 'patchSets/' patchSet '.xml'], ...
            'hmaxHome', [home 'src/hmax-ocv/'], ...
            'nImgs', 150), ...
        'nCategories', 50, ...
        % c3 models
        'organicC3Params', struct( ...
            'c2Dir', [home 'imageSets/imageNet/organicC2Cache/'], ...
            'nModels', 1000, ...
            'patchSet', patchSet, ...
            'minPerClass', 150, ...
            'trainOptions', '-s 0 -t 0 -c 0.1 -b 1 -q', ...
            'repRatio', 1, ...
            'mining', struct('mine',false), ...
            'method', 'svm'), ...
        'inorganicC3Params', struct( ...
            'c2Dir', [home 'imageSets/imageNet/inorganicC2Cache/'], ...
            'nModels', 1000, ...
            'patchSet', patchSet, ...
            'minPerClass', 150, ...
            'trainOptions', '-s 0 -t 0 -c 0.1 -b 1 -q', ...
            'repRatio', 1, ...
            'mining', struct('mine',false), ...
            'method', 'svm'), ...
        % semantic analysis
        'nPairs', 1000, ...
        'featureDir', ensureDir([outDir 'featureCorrelations/']), ...
        'simFile', [home 'src/external/similarity.pl']);
end
