function p = Linear5050Params()
    home = '/home/josh/data/ruleRiesenhuber2013/';
    suffix = 'Linear';
    imgDir = [home 'imageSets/imageNet/'];

    p = struct( ...
        'home', home, ...
        'srcPath', [home 'src/'], ...
        'suffix', suffix, ...
        'imgHome', '/home/josh/maxlab/image-sets/image-net/images/', ...
        'imgDir', imgDir, ...
        'imgExts', {'JPEG'}, ...
        'outDir', ensureDir([home 'evaluation/5050v' suffix '/']), ...
        'nImgs', 150, ...
        'seed', 0, ...
        'nTrainingExamples', [16 32 64 128 256], ...
        'nTestingFeats', [1 2 4 8 16 32 48 64 96 128 192 256 384 512 768 1024 2000 2056], ...
        'nTestingThreshes', [0.3:.05:.9], ...
        'nVisualThreshes', [0.9:.005:0.995], ...
        'nRuns', 20, ...
        'nCVRuns', 5, ...
        'method', 'svm', ...
        'options', '-s 0 -t 0 -b 1 -q -c 0.1', ...
        'c2PatchSets', {{'kmeans', 'twoOhOhSeven'}}, ...
        'c3PatchSets', {{'kmeans'}}, ...
        'caching', struct( ...
            'cacheDir', ensureDir([imgDir 'c2Cache/']), ...
            'maxSize', 240, ...
            'patchDir', [home 'patchSets/'], ...
            'hmaxHome', [home 'src/hmax-ocv/']), ...
        'nTestingCategories', 50, ...
        'organicC3Params', struct( ...
            'c2Dir', [home 'imageSets/imageNet/c2Cache/'], ...
            'nModels', 1000, ...
            'trainOptions', '-s 0 -t 0 -c 0.1 -b 1 -q', ...
            'minPerClass', 150, ...
            'repRatio', 1, ...
            'mining', struct('mine',false), ...
            'method', 'svm'), ...
        'inorganicC3Params', struct( ...
            'c2Dir', [home 'imageSets/imageNet/c2Cache/'], ...
            'nModels', 1000, ...
            'trainOptions', '-s 0 -t 0 -c 0.1 -b 1 -q', ...
            'minPerClass', 150, ...
            'repRatio', 1, ...
            'mining', struct('mine',false), ...
            'method', 'svm'), ...
        'nPairs', 10000, ...
        'featureDir', ensureDir([home 'evaluation/5050v' suffix ...
            '/featureCorrelations/']), ...
        'srFile', '/home2/josh/maxlab/image-sets/image-net/images/structure_released.xml', ...
        'simFile', [home 'src/external/similarity.pl']);
end

function success = ensureDir(dirName)
% Author: Santosh Divvala
% Revised: saurabh.me@gmail.com (Saurabh Singh).
% Revised: rsj28@georgetown.edu (Josh Rule).
%
% Conditionally create a directory and return its path
%
% dirName: string, the absolute path of the directory
%
% success: string, the absolute path of the directory, empty on failure
    if exist(dirName, 'dir') || mkdir(dirName)
        success = dirName;
    else
        success = '';
    end
end
