function p = rbf5050Params()
    home = '/home/josh/data/ruleRiesenhuber2013/';
    suffix = 'RBF';
    imgDir = [home 'imageSets/imageNet/'];
    patchSet = 'kmeans';

    p = struct( ...
        'home', home, ...
        'srcPath', [home 'src/'], ...
        'suffix', suffix, ...
        'imgHome', '/home/josh/maxlab/image-sets/image-net/images/', ...
        'imgDir', imgDir, ...
        'outDir', ensureDir([home 'evaluation/5050v' suffix '/']), ...
        'organicCatFile', [imgDir 'organicCategories.mat'], ...
        'inorganicCatFile', [imgDir 'inorganicCategories.mat'], ...
        'organicImgDir', ensureDir([imgDir 'organicC2Cache/']), ...
        'inorganicImgDir', ensureDir([imgDir 'inorganicC2Cache/']), ...
        'organicC3Dir', [home 'patchSets/organicC3v' suffix '/'], ...
        'inorganicC3Dir', [home 'patchSets/inorganicC3v' suffix '/'], ...
        'seed', 0, ...
        'nTrainingExamples', [16 32 64 128 256], ...
        'nRuns', 20, ...
        'method', 'svm', ...
        'options', '-s 0 -t 2 -b 1 -q', ...
        'patchSet', patchSet, ...
        'caching', struct( ...
            'maxSize', 240, ...
            'patchFile', [home 'patchSets/' patchSet '.xml'], ...
            'hmaxHome', [home 'src/hmax-ocv/'], ...
            'nImgs', 150), ...
        'nCategories', 50, ...
        'organicC3Params', struct( ...
            'c2Dir', [home 'imageSets/imageNet/organicC2Cache/'], ...
            'nModels', 1000, ...
            'patchSet', patchSet, ...
            'minPerClass', 150, ...
            'trainOptions', '-s 0 -t 2 -b 1 -q', ...
            'repRatio', 1, ...
            'mining', struct('mine',false), ...
            'method', 'svm'), ...
        'inorganicC3Params', struct( ...
            'c2Dir', [home 'imageSets/imageNet/inorganicC2Cache/'], ...
            'nModels', 1000, ...
            'patchSet', patchSet, ...
            'minPerClass', 150, ...
            'trainOptions', '-s 0 -t 2 -b 1 -q', ...
            'repRatio', 1, ...
            'mining', struct('mine',false), ...
            'method', 'svm'), ...
        'nPairs', 1000, ...
        'featureDir', ensureDir([home 'evaluation/5050v' suffix ...
            '/featureCorrelations/']), ...
        'simFile', [home 'src/external/similarity.pl']);
end

function success = ensureDir(dirName)
% Author: Santosh Divvala
% Revised: saurabh.me@gmail.com (Saurabh Singh).
% Revised: rsj28@georgetown.edu (Josh Rule).
%
% Conditionally create a directory and return its path
%
% dirName: string, the absolute path of the directory
%
% success: string, the absolute path of the directory, empty on failure
    if exist(dirName, 'dir') || mkdir(dirName)
        success = dirName;
    else
        success = '';
    end
end
