function p = Linear5050Params()
    home = '/data1/josh/ruleRiesenhuber2013/';
    suffix = 'v0_2';
    imgNetHome = '/data2/image_sets/image_net/';

    p = struct( ...
        'home', home, ...
        'srcPaths', {{[home 'src/'],[imgNetHome 'toolbox/']}}, ...
        'seed', 0, ...
        'imgNetDir', [imgNetHome 'images/'], ...
        'imgNetValDir', [imgNetHome 'ILSVRC2015/Data/CLS-LOC/'], ...
        'nImgs', 732, ...
        'nCategories', 2000, ...
        'validationCategoryFile', [imgNetHome 'lists/ilsvrc_obj_loc_train_categories.txt'], ...
        'allCategoryFile', [imgNetHome 'lists/synset_counts.txt'], ...
        'srFile', [imgNetHome 'images/structure_released.xml'], ...
        'imgNetUser', 'joshrule', ...
        'imgNetKey', '8f198f78448a0674277158b595778f55b13ed432', ...
        'suffix', suffix, ...
        'outDir', ensureDir([home 'evaluation/' suffix '/']), ...
        'nTrValidationImgs',25, ...
        'featDir', ensureDir([home 'image_sets/image_net/']), ...
        'maxSize', 256, ...
        'hmaxHome', [home 'src/hmax-ocv/'], ...
        'patchFiles', {{[home 'patchSets/kmeans.xml']}});
%       'nTrainingExamples', [16 32 64 128 256], ...
%       'nTestingFeats', [1 2 4 8 16 32 48 64 96 128 192 256 384 512 768 1024 2000 2056], ...
%       'nTestingThreshes', [0.3:.05:.9], ...
%       'nVisualThreshes', [0.9:.005:0.995], ...
%       'nRuns', 20, ...
%       'nCVRuns', 5, ...
%       'method', 'svm', ...
%       'options', '-s 0 -t 0 -b 1 -q -c 0.1', ...
%       'c3PatchSets', {{'kmeans'}}, ...
%       'organicC3Params', struct( ...
%           'c2Dir', [home 'imageSets/imageNet/c2Cache/'], ...
%           'nModels', 1000, ...
%           'trainOptions', '-s 0 -t 0 -c 0.1 -b 1 -q', ...
%           'minPerClass', 150, ...
%           'repRatio', 1, ...
%           'mining', struct('mine',false), ...
%           'method', 'svm'), ...
%       'inorganicC3Params', struct( ...
%           'c2Dir', [home 'imageSets/imageNet/c2Cache/'], ...
%           'nModels', 1000, ...
%           'trainOptions', '-s 0 -t 0 -c 0.1 -b 1 -q', ...
%           'minPerClass', 150, ...
%           'repRatio', 1, ...
%           'mining', struct('mine',false), ...
%           'method', 'svm'), ...
end

function success = ensureDir(dirName)
% Author: Santosh Divvala
% Revised: saurabh.me@gmail.com (Saurabh Singh).
% Revised: rsj28@georgetown.edu (Josh Rule).
%
% Conditionally create a directory and return its path
%
% dirName: string, the absolute path of the directory
%
% success: string, the absolute path of the directory, empty on failure
    if exist(dirName, 'dir') || mkdir(dirName)
        success = dirName;
    else
        success = '';
    end
end
