function p = params()
% p = params()
%
% Create a parameter structure for running the simulations.
%
% p: structure, the parameters of the simulations
    % The directory containing this project.
    home = '/data1/josh/concept_learning/';
    % The version of the simulations we're running
    suffix = 'v0_2';
    % The directory containing ImageNet.
    imgNetHome = '/data2/image_sets/image_net/';

    p = struct( ...
        % The directory containing this project.
        'home', home, ...
        % The directory containing Caffe.
        'caffe_dir', '/home/josh/caffe/', ...
        % The directories containing source code.
        'srcPaths', {{[home 'src/'],[imgNetHome 'toolbox/']}}, ...
        % The random seed to use.
        'seed', 0, ...
        % The directory containing the main ImageNet images.
        'imgNetDir', [imgNetHome 'images/'], ...
        % The directory containing the ILSVRC ImageNet images.
        'imgNetValDir', [imgNetHome 'ILSVRC2015/'], ...
        % the minimum number of images per category
        'nImgs', 732, ...
        % the number of vocabulary concepts to choose
        'nCategories', 2000, ...
        % where to search for test concepts
        'validationCategoryFile', [imgNetHome 'lists/ilsvrc_obj_loc_train_categories.txt'], ...
        % where to search for vocabulary concepts
        'allCategoryFile', [imgNetHome 'lists/synset_counts.txt'], ...
        % where the ImageNet structure is stored
        'srFile', [imgNetHome 'images/structure_released.xml'], ...
        % ImageNet username
        'imgNetUser', 'joshrule', ...
        % ImageNet password
        'imgNetKey', '8f198f78448a0674277158b595778f55b13ed432', ...
        % the version of the simulations we're running
        'suffix', suffix, ...
        % where to store simulation data
        'outDir', ensureDir([home 'evaluation/' suffix '/']), ...
        % how many network validation images per category
        'nTrValidationImgs',25, ...
        % actually, the edge length of the shortest edge in each image
        'maxSize', 256, ...
        % the directory containing the HMAX binaries
        'hmaxHome', [home 'src/hmax-ocv/'], ...
        % the file containing C2 patches for HMAX
        'patchFiles', {{[home 'patches/kmeans.xml']}}, ...
        % binary evaluation options
        'options', struct( ...
           % where to write evaluation data
           'dir', [home 'evaluation/' suffix '/evaluation_data/'], ...
           % how many images to use total (resample with repetition to hit this number)
           'N', 16000, ...
           % how many GPUS to use
           'nGPUs', 4), ...
        % how many training examples to give binary classifiers in main simulation
        'nBinaryTrainingExamples', [1 2 4 8 16 32 64], ...
        % how many training examples to give binary classifiers in categoricity simulation
        'nCategoricityTrainingExamples', 64, ...
        % how many categories to test
        'nBinaryCategories', 100, ...
        % how many random splits to test for each evaluation
        'nRuns', 20);
end

function success = ensureDir(dirName)
% Author: Santosh Divvala
% Revised: saurabh.me@gmail.com (Saurabh Singh).
% Revised: rsj28@georgetown.edu (Josh Rule).
%
% Conditionally create a directory and return its path
%
% dirName: string, the absolute path of the directory
%
% success: string, the absolute path of the directory, empty on failure
    if exist(dirName, 'dir') || mkdir(dirName)
        success = dirName;
    else
        success = '';
    end
end
